# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d49cc6fb9d8928220c844ea4a8c29e6031301fbb22de967807e99dc73c68f7fdfb1fea1176533da146a79086527e174bc6c42b6ea73975276479aeeebc35968d

test:
  secret_key_base: fa4723aeea25a13e91792ad0c84e122212e646826f3359515530af224260ec5fce6bac0661ca44c38045126f16f44c6261b229f0e445742653debfcdfc0f740f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
